[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["Taiki <taiki.iwahori.bn@furuno.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
black = "^23.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
